(function(){function l(a,b){try{return a[b]}catch(c){return""}}function n(a,b){var c=l(a,b);return null===c||void 0===c?"":"[object String]"===Object.prototype.toString.call(c)?c:p(c)}function q(a,b){function c(){}c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b}function r(a){var b,c,d;a+="=";d=document.cookie.split(";");for(b=0;b<d.length;b++)if(c=d[b],c=c.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""),0===c.indexOf(a))return c.substring(a.length,c.length);return null}
var aa=window.JSON.parse,p=window.JSON.stringify;function t(a){var b=Error.apply(this,arguments);b.name=this.name="InvalidCommandError";this.stack=b.stack;this.message=b.message||a||"The command is invalid"}q(Error,t);function u(a){var b=Error.apply(this,arguments);b.name=this.name="TrackerNotInitializedError";this.stack=b.stack;this.message=b.message||a||"Initialize a tracker first"}q(Error,u);function v(){for(var a="",b=0;36>b;b++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return a}function x(a){return"[object Array]"===Object.prototype.toString.call(a)}function y(a,b,c){this.id=v();this.b=a;this.c=b;this.a=c}function z(a){var b={};b.id=a.id;b.timestamp=a.b;b.url=a.c;b.params=a.a;return b}function A(a,b,c){return(a=a.overriddenBaseUrl)?a+c:b}
function ba(){return"xxxxxxxx-xxxx-6xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})}function B(a,b){var c=[],d;for(d in a)if(a.hasOwnProperty(d)){var e=b?b+"."+d:d,f=a[d];null!==f&&"object"===typeof f?c.push(B(f,e)):c.push(encodeURIComponent(e)+"="+encodeURIComponent(f))}return c.join("&")}function ca(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0}
function da(a){try{var b=a.localStorage;return"undefined"!==typeof b&&(b.setItem("test_nga","test_nga"),"test_nga"===b.getItem("test_nga"))?(b.removeItem("test_nga"),!0):!1}catch(c){return!1}}function C(a){return"undefined"===typeof a}function D(a){return x(a)&&0===a.length}var E,F="storage";function G(){this.a={}}function H(a,b){if(C(b)||C(a.a[b]))throw new t("Handler for key "+b+" doesn't exist");return a.a[b]}function I(a){this.a=a}
I.prototype.send=function(a,b,c,d){var e=new this.a.XMLHttpRequest;e.open(b,"GET"===b&&c?a+"?"+c:a,!0);e.onreadystatechange=function(){4===e.readyState&&e.status&&d.call(this)};e.send("POST"===b?c:void 0)};
function J(a,b,c){this.r=a.p;this.s=a.f;var d={},e={};if(0<b.length){if("string"===typeof b[0])0<b.length&&(e.category=b[0]),1<b.length&&(e.action=b[1]),2<b.length&&(e.label=b[2]),3<b.length&&(e.value=b[3]),4<b.length&&(d=b[4]);else if("object"===typeof b[0])e=b[0],d.customParams=e.customParams||null;else throw new t("Invalid event definition");this.o=n(e,"category");this.d=n(e,"action");this.h=n(e,"label");this.l=n(e,"value")}this.k=A(a,"//ngacm.com/c5t/ev2","ev2");this.i=a.id;this.j=a.userId||r("qeppo_priv_cookie")||
"";this.c=d.customParams||a.customParams||null;this.e=a.clientId||"";this.g=a.version;this.b=c.getTime()}J.prototype.a=function(){var a={};a.epid=this.r;a.eseq=this.s;a.ecat=this.o;a.eact=this.d;a.elab=this.h;a.eval=this.l;a.sid=this.i;a.suid=this.j;a.xp=this.c?p(this.c):"";a.cid=this.e;a.ctv=this.g;a.ccts=this.b;return new y(this.b,this.k,a)};function ea(a,b){var c=a.getContext(),d=new J(c,b,new Date);K(a,{f:c.f+1});return z(d.a())}
function L(a,b,c,d){b=b||{};this.F=function(a){if(!x(a))throw Error("Custom cookies option has to be an array");var b,c={};for(b=0;b<a.length;b++){var d=r(a[b]);d&&(c[a[b]]=d)}return c};this.i=A(a,"//ngacm.com/c5t/pv2","pv2");this.g=a.id;this.h=a.userId||r("qeppo_priv_cookie")||"";this.G=a.sessionId||r("ws2")||"";this.c=b.customParams||a.customParams||null;var e=this.F(b.customCookies||a.customCookies||[]);this.m=!1===ca(e)?e:null;this.d=a.clientId;this.e=a.version;this.l=l(d.location,"href");this.k=
b.referrer||a.referrer||l(d.document,"referrer");this.D=l(d.navigator,"userAgent");this.r=l(d.screen,"width");this.o=l(d.screen,"height");this.j=d.navigator&&d.navigator.cookieEnabled?1:0;this.b=c.getTime();this.s=c.getTimezoneOffset()}
L.prototype.a=function(){var a={};a.sid=this.g;a.suid=this.h;a.ssid=this.G;a.xp=this.c?p(this.c):"";a.xc=this.m?p(this.m):"";a.cid=this.d;a.ctv=this.e;a.crq=this.l;a.crf=this.k;a.cua=this.D;a.csw=this.r;a.csh=this.o;a.cce=this.j;a.ccts=this.b;a.ctz=this.s;a=new y(this.b,this.i,a);a.a.pid=a.id;return a};function fa(a,b){var c=b.pop(),d=new Date,e=a.getContext(),c=(new L(e,c,d,window)).a(),d=e.n?e.p:c.id;K(a,{n:!1});c.a.pid=d;K(a,{p:d,f:e.n?e.f:0});return z(c)}
function M(a,b){b=b||{};var c=b.cookieDomain,d=b.cookieName||"_cmuid",e=b.userId,f=b.sessionId,m=b.customParams,k=b.customCookies,V=b.referrer;this.id=a;this.version=b.overriddenTrackerVersion||"e7b5b1f";this.a={};this.a.p=v();this.a.f=0;this.a.n=!0;if(!c)a:{var c=window.location.hostname,h="allegrogroup.com allegroapi.io allegro.pl allegro.de aukro.cz aukro.ua vatera.hu cokupic.pl otodom.pl otomoto.pl otomoto.eu sendit.pl".split(" "),g;for(g=0;g<h.length;g++){var w=c.indexOf(h[g]);if(-1<w){c="."+
c.substring(w);break a}}c=void 0}this.a.cookieDomain=c;this.a.cookieName=d;c=this.a;h=this.a.cookieDomain;(g=r(d))||(h={B:63072E6,domain:h},g=[""+d+"="+ba()],h.B&&g.push("expires="+(new Date((new Date).getTime()+h.B)).toGMTString()),g.push("path="+(h.path?h.path:"/")),h.domain&&g.push("domain="+h.domain),document.cookie=g.join(";"),g=r(d));c.clientId=g||"";this.a.userId=e;this.a.sessionId=f;this.a.customParams=m;this.a.customCookies=k;this.a.referrer=V;b.overriddenBaseUrl&&(this.a.overriddenBaseUrl=
b.overriddenBaseUrl)}M.prototype.getContext=function(){var a={},b;for(b in this.a)this.a.hasOwnProperty(b)&&(a[b]=this.a[b]);a.id=this.id;a.version=this.version;return a};function K(a,b){for(var c in b)b.hasOwnProperty(c)&&(a.a[c]=b[c])}function N(a,b,c){this.a={};this.c=[];this.d=!1;this.b=a;this.g=b;this.h=c;this.a.create=N.prototype.i;this.a.require=N.prototype.j;this.a.send=N.prototype.k;this.a.set=N.prototype.l}q(G,N);
N.prototype.e=function(){this.c.push(Array.prototype.slice.call(arguments));this.d||O(this)};function ga(a,b){if(x(b))for(var c=0;c<b.length;c++)a.e.apply(a,b[c])}function O(a){for(;a.c.length;){var b=a.c.splice(0,1),c=a,d=b[0];if(D(d))throw new t("No arguments given");var b=d[0].split("@"),e=1<b.length?b[1]:null,d=d.slice(1,d.length);H(c,b[0]).call(c,e,d)}}
N.prototype.i=function(a,b){if(D(b))throw new t;a=b[0];var c=this.b,d=a,e=1<b.length?b[1]:null;c.b=c.b||d;C(c.a[d])?c.a[d]=new M(d,e):console&&console.log("Tracker with id: "+d+" already exists, skip creating.")};N.prototype.j=function(a,b){if(D(b))throw new t;this.d=!0;var c=this;this.h.send(b[0],"GET",null,function(){var a=document.createElement("script"),b=document.getElementsByTagName("script")[0];a.text=this.responseText;b.parentNode.insertBefore(a,b);c.d=!1;O(c)})};
N.prototype.k=function(a,b){var c=P(this.b,a),d=0<b.length?b[0]:"pageview";b=b.slice(1,b.length);var e=this.g,f=b,c=H(e,d).call(null,c,f);ha(e.b,c)};N.prototype.l=function(a,b){if(D(b))throw new t("Second argument of 'set' command has not to be empty");var c=b[0];if("[object Object]"!==Object.prototype.toString.call(c))throw new t("Object is required as a second argument of 'set' command");K(P(this.b,a),c)};q(G,function(){this.a={}});function Q(a,b,c){this.c=a;this.b=b;this.a=c;ia(this)}
function ha(a,b){a.b.t(b);a.send(b,function(){for(var b=R(a.b),d=0;d<b.length;d++)a.a.contains(b[d])||a.send(b[d])})}function ia(a){a.d=function(b,c){return function(){a.b.remove(b);a.a.remove(b);C(c)||c()}}}Q.prototype.send=function(a,b){this.a.t(a);this.c.send(a,this.d(a,b))};function S(){}S.prototype.setItem=function(){};S.prototype.getItem=function(){};function T(){this.a={}}T.prototype.contains=function(a){return!!this.a[a.id]};T.prototype.t=function(a){this.a[a.id]=!0};T.prototype.remove=function(a){delete this.a[a.id]};
function U(a){this.a={};this.b=a;this.a.pageview=fa;this.a.event=ea}q(G,U);function W(a){this.a=a;F=E+"-"+F}q(I,W);W.prototype.send=function(a,b){var c=(new Date).getTime();if(36E5<c-a.timestamp)b();else{var d=a.url,e=a.params;e.csts=c;var c=e,f;for(f in c)null!==c[f]&&void 0!==c[f]&&""!==c[f]||delete c[f];e=B(e);I.prototype.send.call(this,d,"GET",e,b)}};function X(a){this.a=a}X.prototype.t=function(a){var b=R(this);10<=b.length&&(b=b.slice(1,10));b.push(a);this.a.setItem(F,p(b))};
X.prototype.remove=function(a){for(var b=R(this),c=0;c<b.length;c++)b[c].id===a.id&&b.splice(c,1);this.a.setItem(F,p(b))};function R(a){a=aa(a.a.getItem(F)||"[]");a.sort(function(a,c){return a.timestamp-c.timestamp});return a}function ja(){this.b=null;this.a={}}function P(a,b){var c;if(a.a[b])c=a.a[b];else{if(!a.b||!a.a[a.b])throw new u;c=a.a[a.b]}return c}
function ka(a){var b=a["cm.analytics.object"]||"cm";E=b;var c;a[b]&&a[b].q&&(c=a[b].q);var d;da(a)?d=a.localStorage:d=new S;var e=new W(a),f=new I(a),m=new ja;d=new U(new Q(e,new X(d),new T));var k=new N(m,d,f);a[b]=function(){k.e.apply(k,arguments)};a[b].loaded=!0;a[b].registerPlugin=function(a){a(k)};ga(k,c)};ka(window);})();
